### ISSUE TITLE
doesn't install on latest version of android studio

### ISSUE THREAD

**Issue by shafai** [LuigiVampa92/SkyForge#2]
trying to install in Android Studio Hedgehog and it doesn't install.

**Comment by LuigiVampa92** [comment]
Hi, thanks for your interest to the project!

It is true. The plugin was built for the older versions of IntellijIdea/AndroidStudio and because of how Intellij plugin API works, it needs to be manually rebuilt for the latest version to work properly. I plan to do this. Unfortunately I haven't payed enough attention to the project due to my workload since the release of the very first version, but I plan to, because there are also a number of necessary features, improvements and requests from people that need to be added to the plugin. I plan to do all this and publish an updated version within a month. 

Thank you again for your interest and understanding! I will leave this issue open until the problem is resolved

**Comment by shafai** [comment]
I could install it by removing the line
  untilBuild = "223.*"
from the xml. doesn't seem to be needed(?). it works on the latest android studio.

**Comment by LuigiVampa92** [comment]
Hi @shafai sorry for the late answer. I have updated the version recently, it should now support newer versions up to koala. I have made some minor fixes as well, but it seems that some more are needed, because the plugin actions buttons do not display properly in new intellij UI

**Comment by LuigiVampa92** [comment]
Version 0.4.1 from 01.06.2024 is built to work with Android Studio up to the newest Koala. Tested it and everything seems to work fine. Please reopen this issue or create a new one in case of compatibility problems
