### ISSUE TITLE
Rsync is not available error

### ISSUE THREAD

**Issue by shafai** [LuigiVampa92/SkyForge#3]
I use a linux machine to run android studio. after installing the plugin, it gives me this error:
Error: Rsync executable is not available

I do have rsync installed and is working from my command line.
I can't find that error in the source code.

any help?

**Comment by shafai** [comment]
found the issue. I had installed android studio from flatpak which gives it it's own environment.

**Comment by LuigiVampa92** [comment]
Hi, thank you for your interest to the project. Sorry for the late answer, glad to see that the issue was resolved. 

Right now the usage of the plugin depends on the system dependencies directly. I plan to transform it into the docker image. This is not a very easy thing to do, but doing so will make it much less dependent on the environment, OS and distribution, so it will definitely be beneficial

**Comment by shafai** [comment]
no worries and thank you for the project. it was absolutely my noob problem with flatpak. :)
